version: '3.1'

services:

  db:
    image: mysql:8.0.30    
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bataman

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
